import { env } from '@/config/env';
import { logger } from '@/utils/logger';

// Thin wrapper around the pieces of Meta's Graph API needed for a one-click
// "Connect with Facebook" flow on Lead Ads, so a tenant never has to create
// their own Meta app or copy/paste a Page Access Token by hand.
//
// Reference documentation (Meta for Developers):
//  - OAuth dialog + code exchange:   https://developers.facebook.com/docs/facebook-login/guides/advanced/manual-flow
//  - Access token basics:            https://developers.facebook.com/docs/facebook-login/guides/access-tokens
//  - Long-lived token exchange:      https://developers.facebook.com/docs/facebook-login/guides/access-tokens/get-long-lived
//  - Pages a user manages:           https://developers.facebook.com/docs/graph-api/reference/user/accounts/
//  - Page access tokens:             https://developers.facebook.com/docs/pages/access-tokens
//  - Debugging/inspecting a token:   https://developers.facebook.com/docs/facebook-login/guides/access-tokens/debugging-and-error-handling
//  - Webhooks setup & verification:  https://developers.facebook.com/docs/graph-api/webhooks/getting-started
//  - Page subscribed_apps (webhook
//    subscription per page):        https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/
//  - Lead Ads guide (retrieving
//    full lead data via Graph API):  https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving

const graphBase = () => `https://graph.facebook.com/${env.FACEBOOK_GRAPH_VERSION}`;

export class FacebookGraphError extends Error {
  constructor(message: string, public readonly response?: unknown) {
    super(message);
    this.name = 'FacebookGraphError';
  }
}

const assertConfigured = () => {
  if (!env.FACEBOOK_APP_ID || !env.FACEBOOK_APP_SECRET) {
    throw new FacebookGraphError('Facebook integration is not configured on this server (FACEBOOK_APP_ID/FACEBOOK_APP_SECRET missing)');
  }
};

export const buildOAuthUrl = (redirectUri: string, state: string): string => {
  assertConfigured();
  const params = new URLSearchParams({
    client_id: env.FACEBOOK_APP_ID!,
    redirect_uri: redirectUri,
    state,
    response_type: 'code',
    // pages_show_list + pages_manage_metadata: list & subscribe the page's webhook
    // leads_retrieval: read lead data generated by that page's Lead Ads
    scope: 'pages_show_list,pages_manage_metadata,leads_retrieval,pages_read_engagement',
  });
  return `https://www.facebook.com/${env.FACEBOOK_GRAPH_VERSION}/dialog/oauth?${params.toString()}`;
};

export const exchangeCodeForUserToken = async (code: string, redirectUri: string): Promise<string> => {
  assertConfigured();
  const params = new URLSearchParams({
    client_id: env.FACEBOOK_APP_ID!,
    client_secret: env.FACEBOOK_APP_SECRET!,
    redirect_uri: redirectUri,
    code,
  });
  const res = await fetch(`${graphBase()}/oauth/access_token?${params.toString()}`);
  const data = (await res.json()) as any;
  if (!res.ok || !data.access_token) {
    throw new FacebookGraphError('Failed to exchange authorization code for an access token', data);
  }
  return data.access_token as string;
};

// A user token from the OAuth dialog is short-lived (~1-2h). Exchanging it for
// a long-lived token (~60 days) means Page tokens derived from it are
// effectively non-expiring under normal use, per Meta's access token docs.
export const exchangeForLongLivedUserToken = async (shortLivedToken: string): Promise<string> => {
  assertConfigured();
  const params = new URLSearchParams({
    grant_type: 'fb_exchange_token',
    client_id: env.FACEBOOK_APP_ID!,
    client_secret: env.FACEBOOK_APP_SECRET!,
    fb_exchange_token: shortLivedToken,
  });
  const res = await fetch(`${graphBase()}/oauth/access_token?${params.toString()}`);
  const data = (await res.json()) as any;
  if (!res.ok || !data.access_token) {
    throw new FacebookGraphError('Failed to exchange for a long-lived access token', data);
  }
  return data.access_token as string;
};

export interface FacebookPage {
  id: string;
  name: string;
  access_token: string;
}

export const listManagedPages = async (userToken: string): Promise<FacebookPage[]> => {
  const res = await fetch(`${graphBase()}/me/accounts?fields=id,name,access_token&access_token=${encodeURIComponent(userToken)}`);
  const data = (await res.json()) as any;
  if (!res.ok) throw new FacebookGraphError('Failed to list Facebook Pages for this user', data);
  return (data.data || []) as FacebookPage[];
};

// Subscribes the page to leadgen events on our app, replacing the manual
// "Add Product → Webhooks → Subscribe" step in the Meta App Dashboard.
export const subscribePageToLeadgen = async (pageId: string, pageAccessToken: string): Promise<void> => {
  const params = new URLSearchParams({ subscribed_fields: 'leadgen', access_token: pageAccessToken });
  const res = await fetch(`${graphBase()}/${pageId}/subscribed_apps?${params.toString()}`, { method: 'POST' });
  const data = (await res.json()) as any;
  if (!res.ok || !data.success) {
    throw new FacebookGraphError(`Failed to subscribe page ${pageId} to leadgen webhooks`, data);
  }
};

export const unsubscribePage = async (pageId: string, pageAccessToken: string): Promise<void> => {
  try {
    const params = new URLSearchParams({ access_token: pageAccessToken });
    await fetch(`${graphBase()}/${pageId}/subscribed_apps?${params.toString()}`, { method: 'DELETE' });
  } catch (err) {
    logger.warn(`Failed to unsubscribe Facebook page ${pageId} on disconnect (best-effort)`, { err });
  }
};

// Cheap liveness check for the background token-health job — a Page token
// that still resolves the page's own id is still valid.
export const isPageTokenValid = async (pageId: string, pageAccessToken: string): Promise<boolean> => {
  try {
    const res = await fetch(`${graphBase()}/${pageId}?fields=id&access_token=${encodeURIComponent(pageAccessToken)}`);
    if (!res.ok) return false;
    const data = (await res.json()) as any;
    return data.id === pageId;
  } catch {
    return false;
  }
};

export const fetchLeadFieldData = async (leadgenId: string, pageAccessToken: string): Promise<Record<string, string>> => {
  const res = await fetch(`${graphBase()}/${leadgenId}?fields=field_data&access_token=${encodeURIComponent(pageAccessToken)}`);
  if (!res.ok) throw new FacebookGraphError(`Failed to fetch lead ${leadgenId} field data`, await res.json().catch(() => undefined));
  const data = (await res.json()) as any;
  const fields: Record<string, string> = {};
  (data.field_data || []).forEach((f: any) => {
    fields[f.name] = f.values?.[0] || '';
  });
  return fields;
};
